version: 2
jobs:
  get_data:
    machine:
      image: circleci/classic:201711-01
    working_directory: ~/data
    steps:
      - restore_cache:
          keys:
            - data-v2-{{ .Revision }}
            - data-v2-
      - run:
          name: Get ds114_test1
          command: |
            mkdir -p ~/data
            if [[ ! -d ~/data/ds114_test1 ]]; then
              wget -c -O ~/ds114_test1.tar \
              "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e54a326c613b01d7d3ed90" && \
              mkdir -p ~/data && tar xf ~/ds114_test1.tar -C ~/data && \
              rm ~/ds114_test1.tar;
            else
              echo "ds114_test1 was cached"
            fi
      - run:
          name: Get ds114_test2
          command: |
            mkdir -p ~/data
            if [[ ! -d ~/data/ds114_test2 ]]; then
              wget -c -O ~/ds114_test2.tar \
              "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e549f9b83f6901d457d162" && \
              mkdir -p ~/data && tar xf ~/ds114_test2.tar -C ~/data && \
              rm ~/ds114_test2.tar;
            else
              echo "ds114_test2 was cached"
            fi
      - run:
          name: Get ds114_test1_freesurfer
          command: |
            mkdir -p ~/data
            if [[ ! -d ~/data/ds114_test1_freesurfer ]]; then
              wget -c -O ~/ds114_test1_freesurfer.tar \
              "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/5882adf3b83f6901f564da49" && \
              mkdir -p ~/data && tar xf ~/ds114_test1_freesurfer.tar -C ~/data && \
              rm ~/ds114_test1_freesurfer.tar;
            else
              echo "ds114_test1_freesurfer was cached"
            fi
      - run:
          name: Get ds114_test2_freesurfer
          command: |
            mkdir -p ~/data
            if [[ ! -d ~/data/ds114_test2_freesurfer ]]; then
              wget -c -O ~/ds114_test2_freesurfer.tar \
              "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/5882b0e3b83f6901fb64da18" && \
              mkdir -p ~/data && tar xf ~/ds114_test2_freesurfer.tar -C ~/data && \
              rm ~/ds114_test2_freesurfer.tar;
            else
              echo "ds114_test2_freesurfer was cached"
            fi
      - save_cache:
         key: data-v2-{{ .Revision }}-{{ epoch }}
         paths:
            - ~/data

  build_test:
    working_directory: ~/wd
    docker:
      - image: docker:18.01.0-ce-git
    steps:
      - checkout
      - run:
          name: Install parallel gzip
          command: |
            apk add --no-cache pigz
      - restore_cache:
          keys:
            - docker-v1-{{ .Branch }}-{{ .Revision }}
            - docker-v1-{{ .Branch }}-
            - docker-v1-master-
            - docker-v1-
          paths:
            - /tmp/cache/docker.tar.gz
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
            else
              echo "No docker cache found"
            fi
            docker images
      - run:
          name: get version
          command: |
            git describe --tags --always > version
            cat version
      - run:
          name: Build Docker image
          no_output_timeout: 60m
          command: |
            docker images
            set +o pipefail
            docker build --cache-from=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} \
            -t ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest .
            docker images
      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            set +o pipefail
            docker save ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest \
              | pigz -2 -p 3 > /tmp/cache/docker.tar.gz
      - save_cache:
           key: docker-v1-{{ .Branch }}-{{ epoch }}
           paths:
             - /tmp/cache/docker.tar.gz
      # RUN TESTS
      - restore_cache:
          keys:
            - data-v2-{{ .Revision }}
            - data-v2-
      - run:
          name: test1
          command: ls ~/data/ds114_test2_freesurfer
      - run:
          name: Usage BIDS
          command: docker run -ti --rm ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest -h
      - run:
          name: Usage files
          command: docker run --rm -ti --entrypoint=run_brain_age_files.py ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest -h
      - run:
          name: Version BIDS
          command: docker run -ti --rm ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest -v
      - run:
          name: Version files
          command: docker run --rm -ti --entrypoint=run_brain_age_files.py ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest -v



workflows:
  version: 2
  build_test_deploy:
    jobs:
      - get_data:
          filters:
            tags:
              only: /.*/
      - build_test:
          requires:
            - get_data
          filters:
            tags:
              only: /.*/
